// <auto-generated />
using Firewatch.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Firewatch.Database.Migrations
{
    [DbContext(typeof(FirewatchContext))]
    [Migration("20231230123754_UpdateMetricsToImmutable")]
    partial class UpdateMetricsToImmutable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Firewatch.Database.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Metrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Percentage of resource used",
                            Name = "Percent",
                            UnitOfMeasurement = "%"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Amount of Megabytes used by resource",
                            Name = "Megabytes Used",
                            UnitOfMeasurement = "mB"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Total amount of Megabytes available to resource",
                            Name = "Total Megabytes available",
                            UnitOfMeasurement = "mB"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Amount of bytes, sent by given resource",
                            Name = "Bytes sent",
                            UnitOfMeasurement = "b"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Amount of bytes, received by given resource",
                            Name = "Bytes received",
                            UnitOfMeasurement = "b"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The speed of transmission for given resource",
                            Name = "Bytes sent per second",
                            UnitOfMeasurement = "b/sec"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The speed of reception for given resource",
                            Name = "Bytes received per second",
                            UnitOfMeasurement = "b/sec"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Resource temperature",
                            Name = "Temperature",
                            UnitOfMeasurement = "°C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
